development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Ring_de_BOND_development
  pool: 5
  username: railsuser
  password: MyNewPass7!
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Ring_de_BOND_test
  pool: 5
  username: railsuser
  password: MyNewPass7!
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Ring_de_BOND_production
  pool: 5
  username: railsuser
  password: MyNewPass7!
  host: localhost